language: go

go:
  - 1.x
  - 1.6
  - 1.7.x
  - master

os:
  - linux
  - osx

env:
  - LIBGADU_VERSION=1.12.1

before_install:
  - "pushd $PWD"
  - "cd /tmp"
  - "wget http://github.com/wojtekka/libgadu/releases/download/$LIBGADU_VERSION/libgadu-$LIBGADU_VERSION.tar.gz"
  - "tar -zxvf libgadu-$LIBGADU_VERSION.tar.gz"
  - "cd libgadu-$LIBGADU_VERSION"
  - "./configure --prefix=/usr"
  - "make"
  - "sudo make install"
  - "popd"
